#!/bin/bash
# Deploy Script for Backend
cd ..
zip -r upload.zip hackathoners
scp upload.zip ubuntu@13.124.223.111:/home/ubuntu
ssh -tt ubuntu@13.124.223.111 'bash -s' << 'DEPLOY'
sudo systemctl daemon-reload
sudo systemctl stop nginx
sudo systemctl stop hackathoners

sudo unzip -o upload.zip
sudo rm -rf upload.zip

sudo chmod 777 hackathoners

sudo apt-get install -y python3-dev python3-pip
sudo pip3 install -r hackathoners/requirements.txt

sudo systemctl daemon-reload
sudo systemctl start nginx
sudo systemctl start hackathoners
exit
DEPLOY